language: python
python:
  - 2.6
  - 2.7
install:
  - pip install -r requirements.txt --use-mirrors
  - pip install pytest pytest-cov
  - pip install coverage --use-mirrors
script:
  - py.test
after_success:
  - pip install python-coveralls --use-mirrors
  - coveralls
